---

docker_data_root_dir: "/var/lib/docker"

jenkins_admin_username: admin
jenkins_admin_password: password

jenkins_home_dir: "/var/jenkins_home"

jenkins_username: jenkins
jenkins_uid: 386
jenkins_gid: "{{jenkins_uid}}"

jenkins_slave:
  swarm_version: "3.24"
  numExecutorsMultiplier: 1     # Cannot set to "{{ansible_processor_vcpus * 3}}" because ansible_processor_vcpus is a hostvar, only determined when being built.
  docker_network:
    network_mode: host      # e.g.: host or bridge
#    name: "jenkins"
#    cidr: "10.50.0.0/24"

jenkins_master:
  docker:
    repo_dockerfile_path: "/11/debian/buster/hotspot/Dockerfile"    # From: https://github.com/jenkinsci/docker.git
    version: "latest-lts"                                           # One of: 'latest-lts', 'latest', or a legitimate version string (from https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-war/maven-metadata.xml)
  workspace_dir: "{{jenkins_home_dir}}/jobs"
  docker_network:
    network_mode: host      # e.g.: host or bridge
#    name: "jenkins"
#    cidr: "10.50.0.0/24"
  plugins:
    - "basic-branch-build-strategies:latest"
    - "blueocean:latest"
    - "configuration-as-code:latest"
    - "extended-choice-parameter:latest"
    - "git-parameter:latest"
    - "parameterized-scheduler:latest"
    - "permissive-script-security:latest"
    - "pipeline-utility-steps:latest"
    - "rebuild:latest"
    - "swarm:latest"
    - "workflow-aggregator:latest"
  jcasc_numExecutorsMultiplier: 0.5     # Cannot set jenkins_master.casc_config.jenkins.jcasc_numExecutorsMultiplier = "{{ansible_processor_vcpus * 3}}" because ansible_processor_vcpus is a hostvar, only determined when being built.
  casc_file:
    local: "/home/{{jenkins_username}}/jenkins_casc.yml"
    remote: "{{jenkins_home_dir}}/casc_configs/jenkins.yml"
  casc_config:
    jenkins:
      systemMessage: 'Test server'
      authorizationStrategy: "loggedInUsersCanDoAnything"
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: "{{jenkins_admin_username}}"
              password: "{{jenkins_admin_password}}"
    unclassified:
      globalDefaultFlowDurabilityLevel:
        durabilityHint: PERFORMANCE_OPTIMIZED
#    credentials:
#      system:
#        domainCredentials:
#          - credentials:
#              - usernamePassword:
#                  scope: GLOBAL
#                  id: GITHUB_SVC_USER
#                  username: SVC_RO
#                  password: "FAKEPASSWD"
#              - string:
#                  scope: GLOBAL
#                  id: VAULT_PASSWORD_SANDBOX
#                  secret: "FAKEPASSWD"
#              - basicSSHUserPrivateKey:
#                  scope: GLOBAL
#                  id: SANDBOX_SSH_KEY
#                  username: ubuntu
#                  privateKeySource:
#                    directEntry:
#                      privateKey: "FAKEPASSWD"