---

- name: clusterverse | Deploy the cluster
  hosts: localhost
  gather_facts: false
  tasks:
    - assert: { that: "['clusterverse.clusterverse'] is subset(galaxy_collections.keys())", success_msg: "clusterverse collections dependencies are met", fail_msg: "Please ensure the clusterverse collections are installed: ansible-galaxy install -r requirements.yml)" }
      vars: { galaxy_collections: "{{lookup('pipe', 'ansible-galaxy collection list --format=json', errors='ignore') | from_json | json_query('*') | combine }}" }
      tags: ["always"]

    - { include_role: { name: "clusterverse.clusterverse.clean", apply: { tags: ["clusterverse_clean"]} }, tags: ["clusterverse_clean"], when: "clean is defined" }
    - { include_role: { name: "clusterverse.clusterverse.create", apply: { tags: ["clusterverse_create"]} }, tags: ["clusterverse_create"] }
    - { include_role: { name: "clusterverse.clusterverse.dynamic_inventory", apply: { tags: ["always"]} }, tags: ["always"] }

- name: clusterverse | Configure the cluster
  hosts: all:!not_target_hosts
  gather_facts: false
  tasks:
    - { wait_for_connection: "", timeout: 300, tags: ["always"] }
    - { include_role: { name: "clusterverse.clusterverse.config", apply: { tags: ["clusterverse_config"]} }, tags: ["clusterverse_config"] }


###### Application roles
- name: application | load clusterverse dependencies (if excluded due to --skips-tags)
  hosts: all:!not_target_hosts
  tasks:
    - { include_role: { name: "clusterverse.clusterverse._dependencies", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_config' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_config, this will ensure the variables from /cluster_defs are loaded.
    - { include_role: { name: "clusterverse.clusterverse.cluster_hosts", apply: { tags: ["always"] } }, tags: ["always"], when: "'clusterverse_create' not in ansible_run_tags" }      # If we --skip-tags=clusterverse_create, this will ensure cluster_suffix is defined.

- name: application | Jenkins common tasks
  hosts: all:!not_target_hosts
  tasks: [ { include_role: { name: "jenkins/_common", apply: {tags: ["jenkins_common"]} }, tags: ["jenkins_common"] } ]

- name: application | Jenkins controller tasks
  hosts: controller:!not_target_hosts
  tasks: [ { include_role: { name: "jenkins/controller", apply: {tags: ["jenkins_controller"]} }, tags: ["jenkins_controller"] } ]

- name: application | Jenkins agent tasks
  hosts: agent:!not_target_hosts
  tasks: [ { include_role: { name: "jenkins/agent", apply: {tags: ["jenkins_agent"]} }, tags: ["jenkins_agent"] } ]
######


- name: clusterverse | Perform cluster readiness operations
  hosts: localhost
  tasks: [ { include_role: { name: "clusterverse.clusterverse.readiness", apply: { tags: ["clusterverse_readiness"]} }, tags: ["clusterverse_readiness"] } ]
