---

- name: redeploy | Redeploy the cluster
  hosts: localhost
  tasks:
    - assert: { that: "['clusterverse.clusterverse'] is subset(galaxy_collections.keys())", success_msg: "clusterverse collections dependencies are met", fail_msg: "Please ensure the clusterverse collections are installed: ansible-galaxy install -r requirements.yml)" }
      vars: { galaxy_collections: "{{lookup('pipe', 'ansible-galaxy collection list --format=json', errors='ignore') | from_json | json_query('*') | combine }}" }
      tags: ["always"]

    - name: redeploy | Run redeploy
      include_role:
        name: clusterverse.clusterverse.redeploy
      vars:
        mainclusteryml: "cluster.yml"
        predeleterole: ""
