---

roles:
  - name: clusterverse
    src: https://github.com/dseeley/clusterverse
    version: master

#  - name: jenkins
#    src: https://github.com/dseeley/jenkins-ansible
#    version: master


collections:
  - name: dseeley.nested_playbook
    source: https://galaxy.ansible.com

  - name: https://github.com/dseeley/community.libvirt.git
    type: git
    version: develop

  - name: dseeley.esxifree_guest
    source: https://galaxy.ansible.com

  - name: dseeley.inventory_lookup
    source: https://galaxy.ansible.com
