---

roles:
  - name: jenkins
    src: git@github.com:clusterverse/jenkins.git
    version: master


collections:
  - name: clusterverse.clusterverse
    version: ">=4.0.5,<5.0.0"
    source: https://galaxy.ansible.com
