---

- name: Deploy the cluster
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - { name: "Get dependent roles via ansible-galaxy", local_action: "command ansible-galaxy install -r requirements.yml", tags: ["always"] }

    - { include_role: { name: "clusterverse/clean", apply: { tags: ["clusterverse_clean"]} }, tags: ["clusterverse_clean"], when: "clean is defined"  }
    - { include_role: { name: "clusterverse/create", apply: { tags: ["clusterverse_create"]} }, tags: ["clusterverse_create"] }
    - { include_role: { name: "clusterverse/dynamic_inventory", apply: { tags: ["clusterverse_dynamic_inventory"]} }, tags: ["clusterverse_dynamic_inventory"] }

- name: Configure the cluster
  hosts: all
  tasks:
    - { include_role: { name: "clusterverse/config", apply: { tags: ["clusterverse_config"]} }, tags: ["clusterverse_config"] }

###### Application roles
- name: Jenkins common tasks
  hosts: all
  tasks:
    - { name: remove cloud-init, become: yes, apt: {name: "cloud-init", state: absent} }
    - { include_role: { name: "jenkins/_common", apply: {tags: ["jenkins_common"]} }, tags: ["jenkins_common"] }

- name: Jenkins master tasks
  hosts: master
  tasks:
    - { include_role: { name: "jenkins/master", apply: {tags: ["jenkins_master"]} }, tags: ["jenkins_master"] }

- name: Jenkins slave tasks
  hosts: slave
  tasks:
    - { include_role: { name: "jenkins/slave", apply: {tags: ["jenkins_slave"]} }, tags: ["jenkins_slave"] }
######

- name: Perform cluster readiness operations
  hosts: localhost
  connection: local
  tasks:
    - { include_role: { name: "clusterverse/readiness", apply: { tags: ["clusterverse_readiness"]} }, tags: ["clusterverse_readiness"] }
