---

job:
  name: 'clusterverse/clusterverse-release-tag'
  project-type: pipeline
  display-name: 'clusterverse-release-tag'
  description: ''
  disabled: false
  pipeline-scm:
    scm:
      - git:
          url: https://github.com/dseeley/clusterverse.git
          branches:
            - dps_exsi
          credentials-id: GITHUB_SVC_USER
          timeout: 20
    script-path: jenkinsfiles/Jenkinsfile_release_tag