---

- name: jenkins | Install JJB packages from apt repo
  become: yes
  apt:
    pkg: ['jenkins-job-builder']
    update_cache: yes

- name: jenkins | Upgrade JJB packages from pip
  become: yes
  pip:
    name: "jenkins-job-builder"
    state: latest

- name: JJB | Create temporary build directory
  become: yes
  tempfile:
    state: directory
    suffix: JJBTEMP
  register: tmp_build_dir

- name: JJB | Upload jenkins_jobs.ini template
  become: yes
  copy:
    content: |-
      [job_builder]
      ignore_cache=True
      keep_descriptions=False
      recursive=False
      allow_duplicates=False

      [jenkins]
      url=http://127.0.0.1:8080/
      query_plugins_info=False
      user={{ jenkins_admin_username }}
      password={{ jenkins_admin_password }}
    dest: "{{ tmp_build_dir.path }}/jenkins_jobs.ini"
    mode: 0440

- name: JJB | Load the jobs files into 'jjb_jobs' fact
  set_fact:
    jjb_jobs: "{{ jjb_jobs | default([]) + [{(item|basename): ((lookup('template', item) | from_yaml) ) }] }}"
  with_fileglob: "{{ playbook_dir }}/group_vars/{{ clusterid }}/jjb_jobs/*"

- name: JJB | Copy folder jobs to the JJB directory
  become: yes
  blockinfile:
    content: |-
      - job:
          name: "{{item}}"
          project-type: folder
    path: "{{ tmp_build_dir.path }}/_folders-definition.yml"
    create: yes
    marker: "## {mark} ANSIBLE MANAGED BLOCK ({{item}})"
    mode: 0440
  with_items: "{{ _folder_names }}"
  vars:
    _job_names: "{{jjb_jobs | json_query(\"[].*.job.name[]\")}}"
    _folder_names: "{{ _job_names | map ('regex_search', '^(.*?)\/.+$', '\\1') | list | json_query(\"[]\") }}"

- name: JJB | Reload jenkins-jobs (create folders first)
  become: yes
  shell: "jenkins-jobs --conf {{ tmp_build_dir.path }}/jenkins_jobs.ini update {{ tmp_build_dir.path }}"

- name: JJB | Copy jobs to the JJB directory
  become: yes
  copy:
    content: |-
      - job:
          {{ item[_filename].job | to_nice_yaml(indent=2, width=10000) | indent(4, false) }}
    dest: "{{ tmp_build_dir.path }}/{{ _filename }}"
    mode: 0440
  with_items: "{{ jjb_jobs }}"
  vars:
    _filename: "{{ item.keys() | list | first }}"

- name: JJB | Reload jenkins-jobs (add jobs)
  become: yes
  shell: "jenkins-jobs --conf {{ tmp_build_dir.path }}/jenkins_jobs.ini update {{ tmp_build_dir.path }}"

- name: JJB | Remove temporary build directory
  become: yes
  file:
    path: "{{ tmp_build_dir.path }}"
    state: absent
