---

- name: jenkins | Install JJB packages from apt repo
  become: yes
  apt:
    pkg: ['jenkins-job-builder']
    update_cache: yes

- name: jenkins | Upgrade JJB packages from pip
  become: yes
  pip:
    name: "jenkins-job-builder"
    state: latest

- name: JJB | Remove old jobs
  shell: "rm -rf {{jenkins_master.jjb_dir}}/*"

- name: JJB | Upload jenkins_jobs.ini template
  become: yes
  copy:
    content: |-
      [job_builder]
      ignore_cache=True
      keep_descriptions=False
      recursive=False
      allow_duplicates=False

      [jenkins]
      url=http://127.0.0.1:8080/
      query_plugins_info=False
      user={{ jenkins_admin_username }}
      password={{ jenkins_admin_password }}
    dest: "{{ jenkins_master.jjb_dir }}/jenkins_jobs.ini"
    mode: 0440
    owner: 1000
    group: 1000

- name: JJB | Load the jobs files into 'jjb_jobs' fact
  set_fact:
    jjb_jobs: "{{ jjb_jobs | default([]) + [{(item|basename): ((lookup('template', item) | from_yaml) ) }] }}"
  with_fileglob: "{{ playbook_dir }}/group_vars/{{ clusterid }}/jjb_jobs/*"

- name: JJB | Copy folder jobs to the JJB directory
  blockinfile:
    content: |-
      - job:
          name: "{{item}}"
          project-type: folder
    path: "{{ jenkins_master.jjb_dir }}/_folders-definition.yml"
    create: yes
    marker: "## {mark} ANSIBLE MANAGED BLOCK ({{item}})"
    mode: 0440
    owner: 1000
    group: 1000
  with_items: "{{ _folder_names }}"
  vars:
    _job_names: "{{jjb_jobs | json_query(\"[].*.job.name[]\")}}"
    _folder_names: "{{ _job_names | map ('regex_search', '^(.*?)\/.+$', '\\1') | list | json_query(\"[]\") }}"

- name: JJB | Reload jenkins-jobs (add folders first)
  shell: "jenkins-jobs --conf {{ jenkins_master.jjb_dir }}/jenkins_jobs.ini update {{ jenkins_master.jjb_dir }} --workers 0 --delete-old"

- name: JJB | Copy jobs to the JJB directory
  copy:
    content: |-
      - job:
          {{ item[_filename].job | to_nice_yaml(indent=2, width=10000) | indent(4, false) }}
    dest: "{{ jenkins_master.jjb_dir }}/{{ _filename }}"
    mode: 0440
    owner: 1000
    group: 1000
  with_items: "{{ jjb_jobs }}"
  vars:
    _filename: "{{ item.keys() | list | first }}"

- name: JJB | Reload jenkins-jobs (add jobs)
  shell: "jenkins-jobs --conf {{ jenkins_master.jjb_dir }}/jenkins_jobs.ini update {{ jenkins_master.jjb_dir }} --workers 0 --delete-old"