---

- name: "Assert that only 1 master node is being created"
  assert: { that: "groups['master'] | length == 1", msg: "You may only create a single master node." }

- name: Forward 80 and 443 ports using iptables if host networking is being used (or if explicitly reqeusted using -e port_forward=true).
  block:
    - name: jenkins | permanently forward ports 80->8080 and 443->8443 (iptables - Debian/ Ubuntu)
      become: yes
      shell: "{{ item }}"
      loop:
        - "iptables -t nat -A PREROUTING -p tcp -m tcp -i {{ ansible_default_ipv4.interface }} --dport 80 -j REDIRECT --to-ports 8080"    # Redirect traffic inbound on default ipv4 interface (e.g. eth0)
        - "iptables -t nat -I OUTPUT -p tcp -o lo --dport 80 -j REDIRECT --to-ports 8080"                                                 # Redirect traffic outbound on loopback interface (PREROUTING not valid on loopback), for console api access
        - "iptables -t nat -A PREROUTING -p tcp -m tcp -i {{ ansible_default_ipv4.interface }} --dport 443 -j REDIRECT --to-ports 8443"
        - "iptables -t nat -I OUTPUT -p tcp -o lo --dport 443 -j REDIRECT --to-ports 8443"
        - "mkdir -p /etc/iptables && iptables-save > /etc/iptables/rules.v4 && ip6tables-save > /etc/iptables/rules.v6"
      when: ansible_os_family == 'Debian'

    - name: jenkins | permanently forward ports 80->8080 and 443->8443 (firewall-cmd - RedHat/ CentOS)
      become: yes
      shell: "{{ item }}"
      loop:
        - "firewall-cmd --zone=external --permanent --add-forward-port=port=80:proto=tcp:toaddr=127.0.0.1:toport=8080"
        - "firewall-cmd --zone=external --permanent --add-forward-port=port=443:proto=tcp:toaddr=127.0.0.1:toport=8443"
      when: ansible_os_family == 'RedHat'
  when: "jenkins_master.docker_network.network_mode == 'host' or (port_forward is defined and port_forward|bool)"

- name: jenkins | install Jenkins in Docker
  include_tasks: jenkins_in_docker.yml

- name: jenkins | install jjb and jobs
  include_tasks: jjb.yml
