---

merge_dict_vars_list:
  - "./cluster_defs/"
  - "./cluster_defs/{{ cloud_type }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ clusterid }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ clusterid }}/_build_dockerfiles/"
  - "./cluster_defs/{{ cloud_type }}/{{ clusterid }}/{{ region }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ clusterid }}/{{ region }}/{{ buildenv }}/"

jjb_jobs_dir: "./cluster_defs/{{ cloud_type }}/_jjb_jobs"