---

merge_dict_vars_list:
  - "./cluster_defs/"
  - "./cluster_defs/_build_dockerfiles/"
  - "./cluster_defs/{{ cloud_type }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ region }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ buildenv }}/"
  - "./cluster_defs/{{ cloud_type }}/{{ region }}/{{ buildenv }}/"

jjb_jobs_dir: "./cluster_defs/{{ cloud_type }}/_jjb_jobs"