---

- name: Install required packages (gnupg2 for docker GPG key)
  become: yes
  apt:
    name: ['gnupg2', 'python3-pip']
    update_cache: yes

- name: Install docker from Docker repos
  block:
    - name: Create docker data-root dir
      become: yes
      file: 
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{docker_data_root_dir}}"
        - "/etc/docker"

    - name: Add docker config to set data-root to mounted volume
      become: yes
      copy:
        content: |
          {
            "data-root": "{{docker_data_root_dir}}"
          }
        dest: "/etc/docker/daemon.json"
        force: yes

    - name: Add Docker GPG apt Key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: present

    - name: Update apt and install docker-ce
      become: yes
      apt:
        update_cache: yes
        name: docker-ce
        state: latest

    - name: Install Docker Module for Python
      become: yes
      pip:
        name: ['docker']